### POST
POST http://localhost:8042/usuarios/cadastra
Content-Type: application/json

{
  "nome": "Dana",
  "email": "sem@ba"
}

### por nome
GET http://localhost:8042/usuarios/encontrar-por?nome=ana



